import Head from "next/head";
import { api } from "~/utils/api";
import React from "react";
import PostCard from "./components/PostCard";


export default function Home() {
  const { data } = api.post.getPosts.useQuery();
  if (!data) return;
  return (
    <>
      <div className="mx-auto w-screen ">
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className="w-full bg-yellow-400">
            <div className="max-w-7xl m-auto"> 
            <div className="flex  items-center lg:py-0">
              <div className="space-y-5 mx-4 py-10">
                <h1 className="max-w-xl font-serif text-6xl">
                  <span className="underline  decoration-black decoration-4">
                    Medium
                  </span>{" "}
                  is a place to write, read and connect
                </h1>
                <h2>
                  Its easy and free to post your thinking on any topic and
                  connect with millions of readers.
                </h2>
              </div>
            </div>
            </div>
            
          </div>
          <div className="flex max-w-7xl mx-auto justify-center">
            <div className="max-w-7xl flex-1">
              <div className="flex flex-col gap-3 p-2 sm:grid-cols-2 md:gap-6 md:p-6 lg:grid-cols-3">
                <div className="max-w-[40rem]">
                <PostCard post={data} />
                </div>
                
              </div>
            </div>
           
          </div>
        </>
      </div>
    </>
  );
}
