import Head from "next/head";
import PostIntroduction from "./components/PostIntroduction";
import { api } from "~/utils/api";
import React, { useState, useEffect } from "react";

export default function Home() {
  const { data } = api.post.getPosts.useQuery();
  if (!data) return;

  if (!data) return;
  return (
    <>
      <div className="mx-auto w-screen ">
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <div className="w-full bg-yellow-400">
            <div className="flex max-w-7xl items-center   lg:py-0">
              <div className="space-y-5 px-10 py-10">
                <h1 className="max-w-xl font-serif text-6xl">
                  <span className="underline decoration-black decoration-4">
                    Medium
                  </span>{" "}
                  is a place to write, read and connect
                </h1>
                <h2>
                  Its easy and free to post your thinking on any topic and
                  connect with millions of readers.
                </h2>
              </div>
            </div>
          </div>

          <PostIntroduction post={data} />
        </>
      </div>
    </>
  );
}
