import { signIn, signOut, useSession } from "next-auth/react";

import ShoppingItem from '@prisma/client'
import Link from "next/link";
import { useState } from "react";
import Head from "next/head";
import { api } from "~/utils/api";
import NavBar from "./components/NavBar";

export default function Home() {
  // const [item,setItems]= useState <ShoppingItem[]>
  const { data: secretMessage } = api.post.getSecretMessage.useQuery()
  const createUser = api.post.create.useMutation()
  const handleButton =() =>{
    const name ='ThanhLong510'
    createUser.mutate({name})
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <NavBar/>
         <button onClick={handleButton} type="button" className="bg-violet-500 m-28 h-[50px] w-[200px] text-white text-sm p-2 rounded-md transition hover:bg-violet-600">
              Add Long User
            </button>
          <div className="text-2xl ml-28"> {secretMessage} </div>
         
      </>
    </>
  );
}

